name: Java CI
on:
  push:
    branches: [ master, release-* ]
  pull_request:
    branches: [ master, release-* ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [ubuntu-latest, macOS-latest]
        #java: [ '8', '11', '17' ]
        java: [ '8' ]
      fail-fast: false
    name: JAVA ${{ matrix.distribution }} ${{ matrix.java }} OS ${{ matrix.os }} Gradle ${{ matrix.gradle }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build bls library
        run: |
          git submodule update --init --recursive
          cd contrib/dashj-bls
          mvn package -DskipTests
          cd ../..
      - name: Build dashj with Gradle
        run: ./gradlew build
      - name: Upload Test Results and Reports
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}